# path-sync copy -n sdlc
"""Generate terraform files and pytest file for workspace plan tests."""

from __future__ import annotations

from pathlib import Path

import typer

from workspace import models

app = typer.Typer()

VARIABLES_GENERATED_TF = "variables.generated.tf"
MODULES_GENERATED_TF = "modules.generated.tf"
PLAN_SNAPSHOTS_DIR = "plan_snapshots"
PLAN_SNAPSHOTS_ACTUAL_DIR = "plan_snapshots_actual"
TEST_PLAN_SNAPSHOT_PY = "test_plan_snapshot.py"
EXAMPLES_DIR_NAME = "examples"


def generate_variables_tf(config: models.WsConfig) -> str | None:
    exposed = config.exposed_vars()
    if not exposed:
        return None
    lines = ["# Generated by workspace - do not edit manually", ""]
    for var in exposed:
        lines.append("# tflint-ignore: terraform_unused_declarations")
        lines.append(f'variable "{var.name}" {{')
        if var.var_type:
            lines.append(f"  type    = {var.var_type}")
        if var.module_value:
            lines.append(f"  default = {var.module_value}")
        lines.extend(["}", ""])
    return "\n".join(lines)


def parse_include_examples(value: str, config: models.WsConfig) -> list[models.Example]:
    if value == "all":
        return config.examples
    if value == "none":
        return []
    filters = {f.strip() for f in value.split(",")}
    return [
        ex
        for ex in config.examples
        if ex.identifier in filters or (ex.number is not None and str(ex.number) in filters)
    ]


def generate_modules_tf(
    config: models.WsConfig, examples: list[models.Example], ws_dir: Path
) -> str | None:
    if not examples:
        return None
    examples_dir = models.REPO_ROOT / EXAMPLES_DIR_NAME
    rel_examples = f"../../{EXAMPLES_DIR_NAME}"
    lines = ["# Generated by workspace - do not edit manually", ""]
    for ex in examples:
        example_path = ex.example_path(examples_dir)
        title = ex.title_from_dir(examples_dir)
        lines.append(f"# Example {ex.identifier}: {title}")
        lines.append(f'module "ex_{ex.identifier}" {{')
        lines.append(f'  source = "{rel_examples}/{example_path.name}"')
        for var in config.vars_for_example(ex):
            val = f"var.{var.name}" if var.expose_in_workspace else var.module_value
            lines.append(f"  {var.name} = {val}")
        lines.extend(["}", ""])
        lines.append(f'output "ex_{ex.identifier}" {{')
        lines.append(f"  value = module.ex_{ex.identifier}")
        lines.extend(["}", ""])
    return "\n".join(lines)


def generate_pytest_file(config: models.WsConfig) -> str:
    lines = [
        "# Generated by workspace - do not edit manually",
        "from pathlib import Path",
        "",
        "import pytest",
        "",
        f'ACTUAL_DIR = Path(__file__).parent / "{PLAN_SNAPSHOTS_ACTUAL_DIR}"',
        f'EXPECTED_DIR = Path(__file__).parent / "{PLAN_SNAPSHOTS_DIR}"',
        "",
        "# (example_id, sanitized_address, nested)",
        "TEST_CASES = [",
    ]
    for ex in config.examples:
        nested = ex.should_use_nested_snapshots()
        for reg in ex.plan_regressions:
            sanitized = models.sanitize_address(reg.address)
            lines.append(f"    ({repr(ex.identifier)}, {repr(sanitized)}, {nested}),")
    lines.extend(
        [
            "]",
            "",
            "",
            '@pytest.mark.parametrize("example_id,address,nested", TEST_CASES)',
            "def test_plan_snapshot(",
            "    example_id: str, address: str, nested: bool, file_regression",
            ") -> None:",
            '    subpath = f"{example_id}/{address}" if nested else f"{example_id}_{address}"',
            '    actual_file = ACTUAL_DIR / f"{subpath}.yaml"',
            '    expected_file = EXPECTED_DIR / f"{subpath}.yaml"',
            "    assert actual_file.exists(), f'Actual file not found: {actual_file}'",
            "    file_regression.check(actual_file.read_text(), fullpath=expected_file)",
            "",
        ]
    )
    return "\n".join(lines)


def process_workspace(ws_dir: Path, include_examples: str = "all") -> None:
    ws_config = ws_dir / models.WORKSPACE_CONFIG_FILE
    if not ws_config.exists():
        typer.echo(f"Skipping {ws_dir.name}: no {models.WORKSPACE_CONFIG_FILE} found")
        return
    config = models.parse_ws_config(ws_config)
    variables_tf = ws_dir / VARIABLES_GENERATED_TF
    if content := generate_variables_tf(config):
        variables_tf.write_text(content)
        typer.echo(f"  Generated {VARIABLES_GENERATED_TF}")
    elif variables_tf.exists():
        variables_tf.unlink()
        typer.echo(f"  Removed {VARIABLES_GENERATED_TF} (no exposed vars)")
    examples = parse_include_examples(include_examples, config)
    modules_tf = ws_dir / MODULES_GENERATED_TF
    if content := generate_modules_tf(config, examples, ws_dir):
        modules_tf.write_text(content)
        typer.echo(f"  Generated {MODULES_GENERATED_TF} ({len(examples)} examples)")
    elif modules_tf.exists():
        modules_tf.unlink()
        typer.echo(f"  Removed {MODULES_GENERATED_TF} (no examples)")
    (ws_dir / PLAN_SNAPSHOTS_DIR).mkdir(exist_ok=True)
    (ws_dir / PLAN_SNAPSHOTS_ACTUAL_DIR).mkdir(exist_ok=True)
    pytest_file = ws_dir / TEST_PLAN_SNAPSHOT_PY
    pytest_file.write_text(generate_pytest_file(config))
    typer.echo(f"  Generated {TEST_PLAN_SNAPSHOT_PY}")


@app.command()
def main(
    ws: str = typer.Option("all", "--ws", help="Workspace name or 'all' for all ws_* directories"),
    tests_dir: Path = typer.Option(models.DEFAULT_TESTS_DIR, "--tests-dir"),
    include_examples: str = typer.Option("all", "--include-examples", "-e"),
) -> None:
    try:
        ws_dirs = models.resolve_workspaces(ws, tests_dir)
    except ValueError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1)
    for ws_dir in ws_dirs:
        typer.echo(f"Processing {ws_dir.name}...")
        process_workspace(ws_dir, include_examples)
    typer.echo("Done.")


if __name__ == "__main__":
    app()
