formatter: "markdown table"

header-from: main.tf

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  module "atlas_project" {
    source = "terraform-mongodbatlas-modules/project/mongodbatlas"

    name   = "my-project"
    org_id = "5f4d8e9a0123456789abcdef"
  }
  ```

  ## Examples

  - [Basic](./examples/basic) - Minimal project configuration

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
