# path-sync copy -n sdlc
"""Import validation mode: state rm -> generate import blocks -> plan -> assert."""

from __future__ import annotations

import contextlib
import json
import logging
import shutil
from collections.abc import Generator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import typer

from workspace import gen, models, plan

logger = logging.getLogger(__name__)

ATLAS_PREFIX = "mongodbatlas_"
SKIP_SENTINEL = "SKIP"
IMPORTS_GENERATED_TF = "imports.generated.tf"
TFSTATE_FILE = "terraform.tfstate"


@dataclass
class StateResource:
    address: str
    resource_type: str
    values: dict[str, Any]


def extract_state_resources(state_json: dict[str, Any]) -> dict[str, StateResource]:
    result: dict[str, StateResource] = {}
    root = state_json.get("values", {}).get("root_module", {})
    _extract_from_module(root, result)
    return result


def _extract_from_module(module: dict[str, Any], result: dict[str, StateResource]) -> None:
    for resource in module.get("resources", []):
        addr = resource["address"]
        result[addr] = StateResource(
            address=addr,
            resource_type=resource["type"],
            values=resource.get("values", {}),
        )
    for child in module.get("child_modules", []):
        _extract_from_module(child, result)


def validate_atlas_types(atlas_types: set[str], mapping: dict[str, str]) -> None:
    missing = atlas_types - mapping.keys()
    if not missing:
        return
    lines = [f"  {t}: SKIP" for t in sorted(missing)]
    raise ValueError(
        "Unknown mongodbatlas_ types in plan_regressions. "
        "Add to resource_type_import_ids:\n" + "\n".join(lines)
    )


def extract_import_id(
    resource_type: str, attrs: dict[str, Any], mapping: dict[str, str]
) -> str | None:
    if not resource_type.startswith(ATLAS_PREFIX):
        return None
    template = mapping[resource_type]
    if template == SKIP_SENTINEL:
        return None
    try:
        return template.format_map(attrs)
    except KeyError as e:
        raise KeyError(
            f"{resource_type}: template {template!r} references missing state attribute {e}"
        ) from e


def generate_import_blocks_tf(entries: list[tuple[str, str]]) -> str:
    """Generate HCL import blocks. entries = [(address, import_id), ...]."""
    lines = ["# Generated by workspace import validation - do not edit manually", ""]
    for address, import_id in entries:
        lines.append("import {")
        lines.append(f"  to = {address}")
        lines.append(f'  id = "{import_id}"')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


@contextlib.contextmanager
def backup_and_restore_state(ws_dir: Path) -> Generator[None]:
    tfstate = ws_dir / TFSTATE_FILE
    if not tfstate.exists():
        raise ValueError(
            f"{TFSTATE_FILE} not found in {ws_dir.name}. Run --mode apply before --mode import"
        )
    backup = ws_dir / f"{TFSTATE_FILE}.import-backup"
    imports_tf = ws_dir / IMPORTS_GENERATED_TF
    shutil.copy2(tfstate, backup)
    try:
        yield
    finally:
        shutil.copy2(backup, tfstate)
        backup.unlink(missing_ok=True)
        imports_tf.unlink(missing_ok=True)


def assert_import_plan(
    plan_json: dict[str, Any],
    example: models.Example,
) -> list[str]:
    """Return list of assertion failure messages for a single example."""
    failures: list[str] = []
    prefix = f"module.ex_{example.identifier}."
    for rc in plan_json.get("resource_changes", []):
        addr = rc.get("address", "")
        if not addr.startswith(prefix):
            continue
        rel_addr = addr.removeprefix(prefix)
        change = rc.get("change", {})
        actions = change.get("actions", [])
        # TF <=1.12: importing on resource_change; TF 1.13+: under change.importing
        importing = bool(change.get("importing") or rc.get("importing"))

        if actions == ["no-op"] or actions == ["read"]:
            continue

        if "create" in actions or "delete" in actions:
            failures.append(f"{rel_addr}: unexpected actions {actions}")
            continue

        if known := example.import_validation.find_known_change(rel_addr):
            if actions != known.actions:
                failures.append(
                    f"{rel_addr}: expected actions {known.actions}, got {actions}"
                    f" (changed: {sorted(_diff_attributes(change))})"
                )
            elif known.changed_attributes:
                changed = _diff_attributes(change)
                if changed != set(known.changed_attributes):
                    expected = sorted(known.changed_attributes)
                    failures.append(
                        f"{rel_addr}: expected changed_attributes {expected}, got {sorted(changed)}"
                    )
            continue

        changed = _diff_attributes(change)
        if importing:
            failures.append(
                f"{rel_addr}: import drift (actions: {actions}, "
                f"changed: {sorted(changed)}) not in known_changes"
            )
            continue

        failures.append(
            f"{rel_addr}: non-import change with actions {actions}, changed: {sorted(changed)}"
        )

    return failures


def assert_no_destroys(plan_json: dict[str, Any]) -> list[str]:
    return [
        rc.get("address", "?")
        for rc in plan_json.get("resource_changes", [])
        if "delete" in rc.get("change", {}).get("actions", [])
    ]


def assert_clean_plan(plan_json: dict[str, Any], example: models.Example) -> list[str]:
    failures: list[str] = []
    prefix = f"module.ex_{example.identifier}."
    for rc in plan_json.get("resource_changes", []):
        addr = rc.get("address", "")
        if not addr.startswith(prefix):
            continue
        rel_addr = addr.removeprefix(prefix)
        change = rc.get("change", {})
        actions = change.get("actions", [])

        if actions == ["no-op"] or actions == ["read"]:
            continue

        if known := example.import_validation.find_known_change(rel_addr):
            if actions != known.actions:
                failures.append(
                    f"{rel_addr}: expected actions {known.actions}, got {actions}"
                    f" (changed: {sorted(_diff_attributes(change))})"
                )
            elif known.changed_attributes:
                changed = _diff_attributes(change)
                if changed != set(known.changed_attributes):
                    failures.append(
                        f"{rel_addr}: expected changed_attributes "
                        f"{sorted(known.changed_attributes)}, got {sorted(changed)}"
                    )
            continue

        failures.append(
            f"{rel_addr}: expected no-op after apply, got {actions}"
            f" (changed: {sorted(_diff_attributes(change))})"
        )
    return failures


def _diff_attributes(change: dict[str, Any]) -> set[str]:
    """Return attribute names that differ between before and after.

    Attributes marked as after_unknown (shown as 'known after apply' in
    terraform plan) are excluded because their concrete value is not
    available at plan time. Nested after_unknown (list/dict) still counts
    as unknown for the top-level key; an empty dict ``{}`` does not —
    Terraform uses that when the attribute itself is known.
    """
    before = change.get("before", {}) or {}
    after = change.get("after", {}) or {}
    after_unknown = change.get("after_unknown", {}) or {}
    all_keys = set(before) | set(after)
    return {
        k
        for k in all_keys
        if before.get(k) != after.get(k) and not _is_after_unknown(after_unknown.get(k))
    }


def _is_after_unknown(marker: Any) -> bool:
    """True when Terraform marks the attribute (or nested parts) as known after apply."""
    if marker is True:
        return True
    if isinstance(marker, list | dict) and marker:
        return True
    return False


def resolve_import_entries(
    enabled: list[models.Example],
    state_resources: dict[str, StateResource],
    mapping: dict[str, str],
) -> list[tuple[str, str]]:
    """Match enabled plan_regressions to state and build (address, import_id) pairs.

    Raises ValueError when a plan_regressions address is missing from state, or when
    no Atlas resources remain to import-validate after SKIP / non-Atlas filtering.
    """
    missing: list[str] = []
    atlas_types: set[str] = set()
    for ex in enabled:
        for reg in ex.plan_regressions:
            full_addr = f"module.ex_{ex.identifier}.{reg.address}"
            sr = state_resources.get(full_addr)
            if not sr:
                missing.append(full_addr)
                continue
            if sr.resource_type.startswith(ATLAS_PREFIX):
                atlas_types.add(sr.resource_type)

    if missing:
        raise ValueError(
            "plan_regressions addresses missing from state "
            "(run --mode apply first):\n" + "\n".join(f"  {a}" for a in missing)
        )

    validate_atlas_types(atlas_types, mapping)

    import_entries: list[tuple[str, str]] = []
    for ex in enabled:
        for reg in ex.plan_regressions:
            full_addr = f"module.ex_{ex.identifier}.{reg.address}"
            sr = state_resources[full_addr]
            import_id = extract_import_id(sr.resource_type, sr.values, mapping)
            if import_id is None:
                continue
            import_entries.append((full_addr, import_id))

    if not import_entries:
        raise ValueError(
            "No Atlas resources to import-validate. "
            "Disable import_validation or map types in resource_type_import_ids "
            "(use SKIP only when intentional)."
        )
    return import_entries


def process_workspace(
    ws_dir: Path, include_examples: str = "all", var_files: list[Path] | None = None
) -> None:
    ws_config_path = ws_dir / models.WORKSPACE_CONFIG_FILE
    if not ws_config_path.exists():
        logger.info(f"Skipping {ws_dir.name}: no {models.WORKSPACE_CONFIG_FILE} found")
        return
    config = models.parse_ws_config(ws_config_path)
    examples = gen.parse_include_examples(include_examples, config)
    enabled = [ex for ex in examples if ex.import_validation.enabled]
    if not enabled:
        logger.info(f"No examples with import_validation.enabled in {ws_dir.name}, skipping")
        return

    state_json = plan.run_terraform_show_json(ws_dir)
    state_resources = extract_state_resources(state_json)
    import_entries = resolve_import_entries(
        enabled, state_resources, config.resource_type_import_ids
    )
    rm_addresses = [addr for addr, _ in import_entries]

    logger.info(f"Import-validating {len(import_entries)} resources across {len(enabled)} examples")

    with backup_and_restore_state(ws_dir):
        plan.run_terraform_state_rm(ws_dir, rm_addresses)
        imports_tf = ws_dir / IMPORTS_GENERATED_TF
        imports_tf.write_text(generate_import_blocks_tf(import_entries))

        plan.run_terraform_plan(ws_dir, var_files=var_files or [], skip_init=True)
        plan_json_path = ws_dir / plan.PLAN_JSON
        plan_data = json.loads(plan_json_path.read_text())

        all_failures: list[str] = []
        for ex in enabled:
            failures = assert_import_plan(plan_data, ex)
            if failures:
                all_failures.extend(failures)
                for f in failures:
                    logger.error(f"FAIL: {ex.identifier}: {f}")
            else:
                logger.info(f"PASS: {ex.identifier}")

        destroy_addrs = assert_no_destroys(plan_data)
        if destroy_addrs:
            for addr in destroy_addrs:
                logger.error(f"DESTROY: {addr}")
            all_failures.append(
                f"Plan includes {len(destroy_addrs)} destroy action(s). "
                "Refusing to apply. Ensure all examples are included or state is clean."
            )

        if all_failures:
            logger.error(f"Import validation FAILED ({len(all_failures)} failures)")
            raise typer.Exit(1)

        plan.run_terraform_apply_plan(ws_dir)
        imports_tf.unlink(missing_ok=True)

        plan.run_terraform_plan(ws_dir, var_files=var_files or [], skip_init=True)
        plan_data = json.loads(plan_json_path.read_text())

        for ex in enabled:
            failures = assert_clean_plan(plan_data, ex)
            if failures:
                all_failures.extend(failures)
                for f in failures:
                    logger.error(f"FAIL (post-apply): {ex.identifier}: {f}")
            else:
                logger.info(f"PASS (post-apply): {ex.identifier}")

    if all_failures:
        logger.error(f"Import validation FAILED ({len(all_failures)} failures)")
        raise typer.Exit(1)
    logger.info("Import validation passed")
